### ISSUE TITLE
Great module, but usage/require is not intuitive.

### ISSUE THREAD

**Issue by moltar** [StreetStrider/knexed#1]
Not intuitive that need to require a module in a subdir:

```js
const table = require('knexed/table/table')
const join = require('knexed/table/join')
```

Maybe worth adding the example to the docs?

**Comment by StreetStrider** [comment]
@moltar, indeed. I will take a look at that.

**Comment by moltar** [comment]
Если че могу доки поправить )

**Comment by StreetStrider** [comment]
@moltar да я сам 👌 , там всё равно стоит проапдейтить зависимости и протестить на новых версиях Knex-а.

**Comment by StreetStrider** [comment]
@moltar [#api](https://github.com/StreetStrider/knexed#api).

**Comment by StreetStrider** [comment]
Done.
